"use client";

import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, CheckCircle2, CreditCard, LockKeyhole, Mail, ShieldCheck, TicketCheck, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { ProtectedPage } from "@/components/protected-page";
import { stationName } from "@/data/stations";
import { api, ApiError } from "@/lib/api";
import { formatJourneyDate, formatJourneyTime, formatMoney } from "@/lib/format";
import { useAuth } from "@/providers/auth-provider";
import { useToast } from "@/providers/toast-provider";

export function Checkout() {
  const params=useSearchParams(); const router=useRouter(); const {accessToken,user}=useAuth(); const {showToast}=useToast();
  const seatIds=(params.get("seatIds")??params.get("seatId")??"").split(",").filter(Boolean); const seatNumbers=(params.get("seatNumbers")??params.get("seatNumber")??"").split(",").filter(Boolean); const coaches=(params.get("coaches")??params.get("coach")??"").split(",").filter(Boolean);
  const fare=Number(params.get("fare")??0); const currency=params.get("currency")??"LKR"; const originCode=params.get("originCode")??"FOT"; const destinationCode=params.get("destinationCode")??"KDY"; const departure=params.get("departureTime")??new Date().toISOString();
  const [cardName,setCardName]=useState(""); const [cardNumber,setCardNumber]=useState(""); const [expiry,setExpiry]=useState(""); const [cvc,setCvc]=useState(""); const [terms,setTerms]=useState(false);
  const profile=useQuery({queryKey:["profile",accessToken],queryFn:()=>api.profile(accessToken!),enabled:Boolean(accessToken),retry:false});
  const mutation=useMutation({mutationFn:async()=>{const ids=[];for(const seatId of seatIds){const booking=await api.createBooking({tripId:params.get("tripId")!,seatId,originStationId:params.get("originStationId")!,destinationStationId:params.get("destinationStationId")!,paymentMethodToken:`tok_web_${crypto.randomUUID()}`,currency},crypto.randomUUID(),accessToken!);ids.push(booking.id)}return ids},onSuccess:(ids)=>{showToast({tone:"info",title:"Booking started",message:"We’re holding your seat and authorizing payment."});router.push(`/bookings/${ids[0]}${ids.length>1?`?group=${ids.join(",")}`:""}`)},onError:(error)=>showToast({tone:"error",title:"Booking could not start",message:error instanceof ApiError?error.message:"Please check your details and try again."})});
  const cardValid=cardName.trim().length>2&&cardNumber.replaceAll(" ","").length>=12&&expiry.length>=4&&cvc.length>=3&&terms&&seatIds.length>0;
  return <ProtectedPage><main className="booking-flow-page"><div className="page-shell"><div className="flow-nav"><button className="back-link" onClick={()=>router.back()}><ArrowLeft size={16}/>Back to seats</button><div className="flow-steps"><span className="done"><i><CheckCircle2/></i>Seats</span><b className="done"/><span className="active"><i>2</i>Details</span><b/><span><i>3</i>Confirmation</span></div></div><div className="checkout-grid"><section className="checkout-main"><div className="checkout-section"><div className="checkout-section-heading"><span><UserRound/></span><div><small>Passenger contact</small><h1>Who should we notify?</h1></div></div>{profile.isLoading?<div className="profile-skeleton"/>:<div className="passenger-profile"><span className="avatar large">{(profile.data?.fullName??user?.profile.name??"P").toString().slice(0,1)}</span><div><strong>{profile.data?.fullName??user?.profile.name?.toString()??"Passenger"}</strong><span><Mail size={15}/>{profile.data?.email??user?.profile.email?.toString()}</span><small>NIC · {profile.data?.nic??"Verified account"}</small></div><Link href="/profile">Edit</Link></div>}</div>
    <div className="checkout-section"><div className="checkout-section-heading"><span><CreditCard/></span><div><small>Secure payment</small><h2>Payment details</h2></div><span className="secure-chip"><LockKeyhole/>Encrypted</span></div><div className="payment-cards"><span>VISA</span><span>mastercard.</span><span>LANKAQR</span></div><div className="payment-form"><label className="full">Name on card<input value={cardName} onChange={e=>setCardName(e.target.value)} placeholder="Name as printed on card" autoComplete="cc-name"/></label><label className="full">Card number<div className="input-with-icon"><CreditCard/><input value={cardNumber} onChange={e=>setCardNumber(e.target.value.replace(/[^\d ]/g,"").slice(0,19))} placeholder="4242 4242 4242 4242" inputMode="numeric" autoComplete="cc-number"/></div></label><label>Expiry<input value={expiry} onChange={e=>setExpiry(e.target.value.replace(/[^\d/]/g,"").slice(0,5))} placeholder="MM/YY" autoComplete="cc-exp"/></label><label>CVC<input value={cvc} onChange={e=>setCvc(e.target.value.replace(/\D/g,"").slice(0,4))} placeholder="123" inputMode="numeric" autoComplete="cc-csc"/></label></div><p className="demo-payment-note">Demo environment: card details are validated only in the browser; the backend receives a mock provider token.</p></div>
    <label className="terms-check"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>I confirm the passenger details and accept the ticket conditions and cancellation policy.</span></label></section>
    <aside className="order-summary"><span className="eyebrow">Order summary</span><h2>Your railway ticket</h2><div className="ticket-stub"><div className="ticket-stub-top"><span><TicketCheck/></span><div><small>{params.get("trainNumber")?.replaceAll("-"," ")}</small><strong>{stationName(originCode)} → {stationName(destinationCode)}</strong></div></div><div className="ticket-details"><span><small>Date</small><strong>{formatJourneyDate(departure)}</strong></span><span><small>Departure</small><strong>{formatJourneyTime(departure)}</strong></span><span><small>Coach</small><strong>{coaches.join(", ")||"—"}</strong></span><span><small>{seatIds.length>1?"Seats":"Seat"}</small><strong>{seatNumbers.join(", ")||"—"}</strong></span></div></div><div className="price-breakdown"><span>Passenger fare × {seatIds.length}<strong>{formatMoney(fare*seatIds.length,currency)}</strong></span><span>Taxes & booking fee<strong>Included</strong></span><div><span>Total</span><strong>{formatMoney(fare*seatIds.length,currency)}</strong></div></div><button className="button button-primary button-block pay-button" disabled={!cardValid||mutation.isPending} onClick={()=>mutation.mutate()}>{mutation.isPending?"Securing your seats…":`Pay ${formatMoney(fare*seatIds.length,currency)}`}<ArrowRight/></button><p className="secure-note"><ShieldCheck/>Payment and seat confirmation are coordinated safely. You’ll be notified of the final result.</p></aside></div></div></main></ProtectedPage>;
}
