"use client";

import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Check, Circle, Clock3, Download, Home, RefreshCw, ShieldCheck, TicketCheck, XCircle } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { BookingStatusBadge } from "@/components/booking-status";
import { ProtectedPage } from "@/components/protected-page";
import { api } from "@/lib/api";
import { formatJourneyDate, formatMoney } from "@/lib/format";
import { useAuth } from "@/providers/auth-provider";
import type { BookingStatus } from "@/types/api";

const TERMINAL:BookingStatus[]=["CONFIRMED","SEAT_UNAVAILABLE","PAYMENT_FAILED","HOLD_EXPIRED","REFUNDED","FAILED"];
export default function BookingDetailPage(){const {id}=useParams<{id:string}>();const {accessToken}=useAuth();const booking=useQuery({queryKey:["booking",id,accessToken],queryFn:()=>api.booking(id,accessToken!),enabled:Boolean(accessToken),refetchInterval:(query)=>TERMINAL.includes(query.state.data?.status as BookingStatus)?false:2500});
  if(booking.isLoading)return <ProtectedPage><main className="centered-page"><div className="loading-card"><h1>Following your booking</h1><p>Seat and payment updates appear here automatically.</p><div className="loading-bar"/></div></main></ProtectedPage>;
  if(booking.isError||!booking.data)return <ProtectedPage><main className="centered-page"><div className="not-found-card"><XCircle/><h1>Booking not found</h1><p>Check the link or return to your booking history.</p><Link className="button button-primary" href="/bookings">My bookings</Link></div></main></ProtectedPage>;
  const value=booking.data;const success=value.status==="CONFIRMED";const failed=["SEAT_UNAVAILABLE","PAYMENT_FAILED","HOLD_EXPIRED","FAILED","REFUNDED"].includes(value.status);const seatDone=!['PENDING','SEAT_UNAVAILABLE'].includes(value.status);const paymentDone=['PAYMENT_AUTHORIZED','CONFIRMED','REFUND_PENDING','REFUNDED'].includes(value.status);
  return <ProtectedPage><main className="confirmation-page"><div className="page-shell confirmation-shell"><Link className="back-link" href="/bookings"><ArrowLeft/>All bookings</Link><section className={`confirmation-hero ${success?"confirmed":failed?"failed":"processing"}`}><span className="confirmation-icon">{success?<TicketCheck/>:failed?<XCircle/>:<Clock3/>}</span><small>{success?"BOOKING CONFIRMED":failed?"BOOKING UPDATE":"CONFIRMATION IN PROGRESS"}</small><h1>{success?"You’re all set for the journey.":failed?"This booking could not be completed.":"We’re securing your seat."}</h1><p>{success?"Your digital ticket is ready below. We’ve also added a notification to your account.":failed?(value.failureReason??"No payment will be retained for an unsuccessful booking."):"You can keep this page open. It refreshes automatically as inventory and payment complete."}</p><BookingStatusBadge status={value.status}/></section>
    <div className="confirmation-grid"><section className="digital-ticket"><div className="ticket-brand"><span><TicketCheck/></span><div><strong>HelaMaga Sync</strong><small>Digital reserved ticket</small></div><i>{value.status}</i></div><div className="ticket-id"><small>BOOKING REFERENCE</small><strong>{value.id.slice(0,8).toUpperCase()}</strong></div><div className="ticket-info-grid"><span><small>Travel date</small><strong>{formatJourneyDate(value.createdAt)}</strong></span><span><small>Fare</small><strong>{formatMoney(value.quotedAmount,value.currency)}</strong></span><span><small>Trip ID</small><strong>{value.tripId.slice(0,8).toUpperCase()}</strong></span><span><small>Seat ID</small><strong>{value.seatId.slice(0,8).toUpperCase()}</strong></span></div><div className="ticket-barcode" aria-label={`Booking reference ${value.id}`}><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="ticket-actions"><button className="button button-secondary" disabled={!success}><Download/>Download ticket</button><Link className="button button-primary" href="/"><Home/>Home</Link></div></section>
    <aside className="booking-progress"><span className="eyebrow">Booking progress</span><h2>What’s happening</h2><div className="progress-steps"><div className="complete"><i><Check/></i><span><strong>Request received</strong><small>Your idempotent booking was created.</small></span></div><div className={seatDone?"complete":failed?"failed":"active"}><i>{seatDone?<Check/>:failed?<XCircle/>:<RefreshCw/>}</i><span><strong>Seat reserved</strong><small>Inventory checks every segment of your journey.</small></span></div><div className={paymentDone?"complete":failed?"failed":seatDone?"active":""}><i>{paymentDone?<Check/>:failed?<XCircle/>:<Circle/>}</i><span><strong>Payment authorized</strong><small>Payment and seat confirmation are coordinated.</small></span></div><div className={success?"complete":failed?"failed":""}><i>{success?<Check/>:failed?<XCircle/>:<Circle/>}</i><span><strong>Ticket confirmed</strong><small>Your final travel record is issued.</small></span></div></div><div className="protection-note"><ShieldCheck/><div><strong>Protected booking</strong><p>If payment succeeds but the seat cannot be confirmed, the Saga automatically requests a refund.</p></div></div></aside></div></div></main></ProtectedPage>;
}
